############################
# FONT
############################
font_family      Noto Sans Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

############################
# WINDOW
############################
window_padding_width 10
background_opacity 0.95

# dimensione iniziale (pixel)
initial_window_width 1200
initial_window_height 800

# comportamento
confirm_os_window_close 0
copy_on_select yes

############################
# CURSOR
############################
cursor_shape block
cursor_blink_interval 0.5

############################
# SCROLLBACK
############################
scrollback_lines 10000

############################
# PERFORMANCE
############################
enable_audio_bell no
repaint_delay 10
input_delay 3
sync_to_monitor yes

############################
# CLIPBOARD
############################
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

############################
# FULLSCREEN
############################
map alt+enter toggle_fullscreen

############################
# NEW WINDOW / TAB
############################

# tab
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab

############################
# SPLITS (tmux-like)
############################
map ctrl+shift+e launch --location=vsplit
map ctrl+shift+o launch --location=hsplit

############################
# NAVIGAZIONE SPLIT
############################
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

############################
# RESIZE SPLIT
############################
map ctrl+shift+left  previous_tab
map ctrl+shift+right next_tab

# BEGIN_KITTY_THEME
# Ayaka
include current-theme.conf
# END_KITTY_THEME
