[window]
dynamic_padding = true
decorations = "full"
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"

  [window.padding]
  x = 10
  y = 10

  [window.dimensions]
  columns = 160
  lines = 40

[general]
import = [ "~/.config/alacritty/themes/selected" ]

[font]
size = 12

  [font.normal]
  family = "Noto Sans Mono"
  style = "Regular"

  [font.bold]
  family = "Noto Sans Mono"
  style = "Bold"

  [font.italic]
  family = "Noto Sans Mono"
  style = "Italic"

  [font.bold_italic]
  family = "Noto Sans Mono"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

[cursor]
unfocused_hollow = true

  [cursor.style]
  shape = "Block"
  blinking = "On"

[scrolling]
history = 10_000
multiplier = 3

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"
