#!/bin/bash

yay -S zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting zsh-completions starship fzf find-the-command-git --needed --noconfirm
touch ~/.histfile
chsh -s /bin/zsh
