#!/bin/bash
read -p "Do you want to install AUR packages (y/n) " yn

pkglist_aur=""

echo -e "$pkglist_aur" > pkglist_aur

yay -S --noconfirm --needed paru

case $yn in
	y )	paru -S --noconfirm --needed - < pkglist_aur;;
	* ) echo continue;;
esac

rm -rf pkglist_aur
