#!/bin/bash

pkglist="micro
barrier
btop
htop
man-db
bat
ncdu
dust
duf
dua-cli
trash-cli
lazygit
ranger
ripgrep
neovim
neofetch
xsel
fd
lsd
ncdu
iotop
stress
dfc
snapper
zoxide
diskus
tailscale
exfatprogs
"

echo -e "$pkglist" > pkglist
sudo pacman -S --noconfirm --needed - < pkglist
rm -rf pkglist



